@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cuboiddroid.cuboidmod.modules.collapser.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;